version: "2"
services:
  node:
    image: "rodolpheche/wiremock"
    environment: 
      - uid=${UID}
    volumes:
      - ./mappings:/home/wiremock/mappings
    expose:
      - "8080"
      - "8443"
    ports: 
      - "8080:8080"
    command: ["--global-response-templating"]