version: "2"
services:
  node:
    image: "node:latest"
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    expose:
      - "8081"
    ports: 
      - "8081:8081"
    command: "npm start"